#DISPLAY-NAME IS ALSO NAME USED FOR THE EVENT TRIGGER

Abilities:
  UNNAMED:
    Cooldowns:
      Primary: 1
      Secondary: 1
      Ultimate: 1
    Class: "&f&lMOVEMENT"
    DisplayName: "&#6cff9e&lS&#68f4ad&lp&#65e9bc&le&#61decb&lc&#5ed3da&lt&#5ac8e9&lr&#57bdf8&le &#57bdf8&lA&#5ac8e9&lb&#5ed3da&li&#61decb&ll&#65e9bc&li&#68f4ad&lt&#6cff9e&ly"
  ARTIFICER:
    Cooldowns:
      Primary: 1
      Secondary: 1
      Ultimate: 1
    Class: ""
    DisplayName: "&f&lArtificer Ability"
  CATALYST:
    Cooldowns:
      Primary: 1
      Secondary: 1
      Ultimate: 1
    Class: ""
    DisplayName: "&f&lCatalyst Ability"
  EARTH:
    Cooldowns:
      Primary: 1
      Secondary: 1
      Ultimate: 1
    Class: ""
    DisplayName: "&f&lEarth Ability"
  FEATHERWEIGHT:
    Cooldowns:
      Primary: 1
      Secondary: 1
      Ultimate: 1
    Class: ""
    DisplayName: "&f&lFeatherweight Ability"
  STEALTH:
    Cooldowns:
      Primary: 1
      Secondary: 1
      Ultimate: 1
    Class: ""
    DisplayName: "&f&lStealth Ability"
  TRACKER:
    Cooldowns:
      Primary: 1
      Secondary: 1
      Ultimate: 1
    Class: ""
    DisplayName: "&f&lTracker Ability"
  DISCHARGE:
    Cooldowns:
      Primary: 1
      Secondary: 1
      Ultimate: 1
    Class: ""
    DisplayName: "&f&lDischarge Ability"


