name: Kiul-Abilities-V2
version: '${project.version}'
main: kiul.kiulabilities.Kiulabilities
api-version: 1.19
authors: [ kiul, neko, Patty ]
description: kiul's abilities for pat events
commands:
  test:
    description: allows you to test abilities in devevlopment
  giveultpoint:
    description: gives the user one ultimate point
  resetactionbar:
    description: reset the current actionbar for all players
  spawnlootcrate:
    description: spawns a loot crate randomly in the world border
  cata:
    description: spawns a loot crate randomly in the world border
