name: Kiul-Abilities-V2
version: '1.0-SNAPSHOT'
main: kiul.kiulabilities.Kiulabilities
api-version: 1.19
authors: [ kiul, neko ]
description: kiul's abilities for pat events
commands:
  test:
    description: allows you to test abilities in devevlopment
  giveultpoint:
    description: gives the user one ultimate point
